// src/lib/shippingLocations.js

export const SHIPPING_LOCATIONS = {
  domestic: [
    {
      provider: 'GIG Logistics',
      options: [
        { id: 'gig-north', name: 'North', fee: 4600 },
        { id: 'gig-south-main', name: 'South Main Cities', fee: 5500 },
        { id: 'gig-south-onforwarding', name: 'South Onforwarding Cities', fee: 6500 },
        { id: 'gig-special-cities', name: 'Special Cities (Calabar, Uyo, Akure, etc.)', fee: 6500 },
      ]
    },
    {
      provider: 'DHL Nigeria',
      options: [
        { id: 'dhl-north-central', name: 'North & North Central', fee: 5500 },
        { id: 'dhl-north-remote', name: 'Remote North Locations', fee: 7500 },
        { id: 'dhl-south-west', name: 'South/West & South East (Zone B)', fee: 5500 },
        { id: 'dhl-south-remote', name: 'Remote South West Locations', fee: 7500 },
        { id: 'dhl-south-south', name: 'South/South, South/West & South East', fee: 11700 },
        { id: 'dhl-south-south-remote', name: 'Remote South/South & South East', fee: 14000 },
      ]
    }
  ],
  international: [
    {
      provider: 'DHL International',
      options: [
        { id: 'int-zone1', name: 'Zone 1 (UK, Ireland, etc.)', fee: 65000 },
        { id: 'int-zone2', name: 'Zone 2 (West Africa)', fee: 72000 },
        { id: 'int-zone3', name: 'Zone 3 (USA, Canada, Mexico)', fee: 79000 },
        { id: 'int-zone4', name: 'Zone 4 (Europe)', fee: 87000 },
        { id: 'int-zone5', name: 'Zone 5 (Africa)', fee: 93000 },
        { id: 'int-zone6', name: 'Zone 6 (Middle East)', fee: 96000 },
        { id: 'int-zone7', name: 'Zone 7 (Asia & Australia)', fee: 104000 },
        { id: 'int-zone8', name: 'Zone 8 (Americas & Oceania)', fee: 108000 },
      ]
    }
  ]
};

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];