// src/lib/shippingConfig.js

export const COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

// Nigerian states mapping to shipping zones
export const NIGERIAN_STATES = {
    // GIG Logistics Zones
    'Lagos': { gig: 'south-main', dhl: 'south-west' },
    'Abuja': { gig: 'north', dhl: 'north-central' },
    'Rivers': { gig: 'south-main', dhl: 'south-south' },
    'Delta': { gig: 'south-main', dhl: 'south-south' },
    'Anambra': { gig: 'south-onforwarding', dhl: 'south-south' },
    'Enugu': { gig: 'south-onforwarding', dhl: 'south-south' },
    'Imo': { gig: 'south-onforwarding', dhl: 'south-south' },
    'Ogun': { gig: 'south-main', dhl: 'south-west' },
    'Oyo': { gig: 'south-main', dhl: 'south-west' },
    'Kano': { gig: 'north', dhl: 'north-remote' },
    'Kaduna': { gig: 'north', dhl: 'north-central' },
    'Edo': { gig: 'south-main', dhl: 'south-south' },
    'Plateau': { gig: 'north', dhl: 'north-central' },
    'Cross River': { gig: 'special-cities', dhl: 'south-south-remote' },
    'Akwa Ibom': { gig: 'special-cities', dhl: 'south-south-remote' },
    'Ondo': { gig: 'special-cities', dhl: 'south-west' },
    'Kwara': { gig: 'north', dhl: 'north-central' },
    'Bayelsa': { gig: 'south-onforwarding', dhl: 'south-south-remote' },
    'Osun': { gig: 'south-main', dhl: 'south-west' },
    'Benue': { gig: 'north', dhl: 'north-central' },
    'Nasarawa': { gig: 'north', dhl: 'north-central' },
    'Niger': { gig: 'north', dhl: 'north-remote' },
    'Borno': { gig: 'north', dhl: 'north-remote' },
    'Adamawa': { gig: 'north', dhl: 'north-remote' },
    'Taraba': { gig: 'north', dhl: 'north-remote' },
    'Gombe': { gig: 'north', dhl: 'north-remote' },
    'Yobe': { gig: 'north', dhl: 'north-remote' },
    'Zamfara': { gig: 'north', dhl: 'north-remote' },
    'Kebbi': { gig: 'north', dhl: 'north-remote' },
    'Sokoto': { gig: 'north', dhl: 'north-remote' },
    'Katsina': { gig: 'north', dhl: 'north-remote' },
    'Jigawa': { gig: 'north', dhl: 'north-remote' },
    'Bauchi': { gig: 'north', dhl: 'north-remote' },
    'Ekiti': { gig: 'special-cities', dhl: 'south-west' },
    'Ebonyi': { gig: 'south-onforwarding', dhl: 'south-south' },
    'Abia': { gig: 'south-onforwarding', dhl: 'south-south' }
};

// Base shipping rates
export const SHIPPING_RATES = {
    domestic: {
        'GIG Logistics': {
            'north': 4600,
            'south-main': 5500,
            'south-onforwarding': 6500,
            'special-cities': 6500
        },
        'DHL Nigeria': {
            'north-central': 5500,
            'north-remote': 7500,
            'south-west': 5500,
            'south-remote': 7500,
            'south-south': 11700,
            'south-south-remote': 14000
        }
    },
    international: {
        'DHL International': {
            'zone1': 65000, // UK, Ireland
            'zone2': 72000, // West Africa
            'zone3': 79000, // USA, Canada, Mexico
            'zone4': 87000, // Europe
            'zone5': 93000, // Africa
            'zone6': 96000, // Middle East
            'zone7': 104000, // Asia & Australia
            'zone8': 108000 // Americas & Oceania
        }
    }
};

// International zones mapping
export const INTERNATIONAL_ZONES = {
    'United Kingdom': 'zone1',
    'Ireland': 'zone1',
    'United States': 'zone3',
    'Canada': 'zone3',
    'Ghana': 'zone2',
    'South Africa': 'zone5',
    'Germany': 'zone4',
    'France': 'zone4',
    'China': 'zone7',
    'Australia': 'zone7',
    'United Arab Emirates': 'zone6',
    // Add more countries as needed
};