// src/lib/shippingConfig.js

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// Nigerian states mapping to shipping zones - CORRECTED FOR GUO
export const NIGERIAN_STATES = {
  // GIG Logistics Zones
  Lagos: {
    gig: "south-main",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available for Western states only
  },
  Abuja: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Rivers: {
    gig: "south-main",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Delta: {
    gig: "south-main",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Anambra: {
    gig: "south-onforwarding",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Enugu: {
    gig: "south-onforwarding",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Imo: {
    gig: "south-onforwarding",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Ogun: {
    gig: "south-main",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Oyo: {
    gig: "south-main",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Kano: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Kaduna: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Edo: {
    gig: "south-main",
    dhl: "zone-b-south",
    guo: "western-states", // GUO available - same as Lagos
  },
  Plateau: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  "Cross River": {
    gig: "special-cities",
    dhl: "zone-b-south",
    guo: null, // NO GUO - You said GUO only for Western states
  },
  "Akwa Ibom": {
    gig: "special-cities",
    dhl: "zone-b-south",
    guo: null, // NO GUO - You said GUO only for Western states
  },
  Ondo: {
    gig: "special-cities",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Kwara: {
    gig: "north",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Bayelsa: {
    gig: "special-cities",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Osun: {
    gig: "south-main",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Benue: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Nasarawa: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Niger: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Borno: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Adamawa: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Taraba: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Gombe: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Yobe: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Zamfara: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Kebbi: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Sokoto: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Katsina: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Jigawa: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Bauchi: {
    gig: "north",
    dhl: "zone-a",
    guo: null, // NO GUO
  },
  Ekiti: {
    gig: "special-cities",
    dhl: "zone-b-lagos",
    guo: "western-states", // GUO available - same as Lagos
  },
  Ebonyi: {
    gig: "south-onforwarding",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
  Abia: {
    gig: "south-onforwarding",
    dhl: "zone-b-south",
    guo: null, // NO GUO
  },
};

// Base shipping rates - CORRECTED FOR YOUR REQUIREMENTS
export const SHIPPING_RATES = {
  domestic: {
    "GIG Logistics": {
      north: 100,
      "south-main": 100,
      "south-onforwarding": 100,
      "special-cities": 100,
    },
    "GUO Logistics": {
      "western-states": 100,
      "western-states-high-value": 100,
    },
    "DHL Nigeria": {
      "zone-a": 100,
      "zone-a-remote": 100,
      "zone-b-lagos": 100,
      "zone-b-lagos-remote": 100,
      "zone-b-south": 100,
      "zone-b-south-remote": 100,
    },
  },
  international: {
    "DHL International": {
      zone1: 100,
      zone2: 100,
      zone3: 100,
      zone4: 100,
      zone5: 100,
      zone6: 100,
      zone7: 100,
      zone8: 100,
    },
  },
};

// Helper function to check if order value requires high-value shipping - UPDATED
export const getGUORate = (stateData, subtotal) => {
  if (!stateData || !stateData.guo) return null;

  // Apply high-value rates for orders above 100,000 Naira
  if (subtotal >= 100000) {
    // For Western states (all use the same pricing)
    if (stateData.guo === "western-states") {
      return SHIPPING_RATES.domestic["GUO Logistics"][
        "western-states-high-value"
      ];
    }
  }

  // Return standard rate
  return SHIPPING_RATES.domestic["GUO Logistics"][stateData.guo];
};

// Define which states get GUO service (Western states only)
export const GUO_WESTERN_STATES = [
  "Lagos",
  "Ogun",
  "Oyo",
  "Osun",
  "Ondo",
  "Ekiti",
  "Edo",
  "Kwara",
];

// International zones mapping - Updated with complete list from document
export const INTERNATIONAL_ZONES = {
  // Zone 1
  Guernsey: "zone1",
  Ireland: "zone1",
  Jersey: "zone1",
  "United Kingdom": "zone1",

  // Zone 2 - West Africa
  Benin: "zone2",
  "Burkina Faso": "zone2",
  Cameroon: "zone2",
  "Cape Verde": "zone2",
  "Central African Republic": "zone2",
  Chad: "zone2",
  "Cote D'Ivoire": "zone2",
  Congo: "zone2",
  "Congo, Democratic Republic": "zone2",
  Gabon: "zone2",
  Gambia: "zone2",
  Ghana: "zone2",
  Guinea: "zone2",
  "Guinea-Bissau": "zone2",
  Liberia: "zone2",
  Mali: "zone2",
  Niger: "zone2",
  "Sao Tome and Principe": "zone2",
  Senegal: "zone2",
  "Sierra Leone": "zone2",
  Togo: "zone2",

  // Zone 3 - North America
  Canada: "zone3",
  Mexico: "zone3",
  "United States": "zone3",

  // Zone 4 - Europe
  Albania: "zone4",
  Andorra: "zone4",
  Austria: "zone4",
  Belarus: "zone4",
  Belgium: "zone4",
  "Bosnia and Herzegovina": "zone4",
  Bulgaria: "zone4",
  "Canary Island": "zone4",
  Croatia: "zone4",
  Cyprus: "zone4",
  "Czech Republic": "zone4",
  Denmark: "zone4",
  Estonia: "zone4",
  "Faroe Islands": "zone4",
  Finland: "zone4",
  France: "zone4",
  Germany: "zone4",
  Gibraltar: "zone4",
  Greece: "zone4",
  Greenland: "zone4",
  Hungary: "zone4",
  Iceland: "zone4",
  Italy: "zone4",
  Kosovo: "zone4",
  Latvia: "zone4",
  Liechtenstein: "zone4",
  Lithuania: "zone4",
  Luxembourg: "zone4",
  Malta: "zone4",
  Moldova: "zone4",
  Monaco: "zone4",
  Montenegro: "zone4",
  Netherlands: "zone4",
  "North Macedonia": "zone4",
  Norway: "zone4",
  Poland: "zone4",
  Portugal: "zone4",
  Romania: "zone4",
  Russia: "zone4",
  "San Marino": "zone4",
  Serbia: "zone4",
  Slovakia: "zone4",
  Slovenia: "zone4",
  Spain: "zone4",
  Sweden: "zone4",
  Switzerland: "zone4",
  Turkey: "zone4",
  Ukraine: "zone4",

  // Zone 5 - Africa
  Algeria: "zone5",
  Angola: "zone5",
  Botswana: "zone5",
  Burundi: "zone5",
  Comoros: "zone5",
  Djibouti: "zone5",
  Egypt: "zone5",
  Eritrea: "zone5",
  Ethiopia: "zone5",
  Kenya: "zone5",
  Lesotho: "zone5",
  Libya: "zone5",
  Madagascar: "zone5",
  Malawi: "zone5",
  Mauritania: "zone5",
  Mauritius: "zone5",
  Mayotte: "zone5",
  Morocco: "zone5",
  Mozambique: "zone5",
  Namibia: "zone5",
  "Reunion Island": "zone5",
  Rwanda: "zone5",
  Seychelles: "zone5",
  Somalia: "zone5",
  Somaliland: "zone5",
  "South Africa": "zone5",
  "South Sudan": "zone5",
  Sudan: "zone5",
  Swaziland: "zone5",
  Tanzania: "zone5",
  Tunisia: "zone5",
  Uganda: "zone5",
  Zambia: "zone5",
  Zimbabwe: "zone5",

  // Zone 6 - Middle East
  Afghanistan: "zone6",
  Bahrain: "zone6",
  Iran: "zone6",
  Iraq: "zone6",
  Israel: "zone6",
  Jordan: "zone6",
  Kuwait: "zone6",
  Lebanon: "zone6",
  Oman: "zone6",
  Qatar: "zone6",
  "Saudi Arabia": "zone6",
  Syria: "zone6",
  "United Arab Emirates": "zone6",
  Yemen: "zone6",

  // Zone 7 - Asia & Australia
  Armenia: "zone7",
  Australia: "zone7",
  Azerbaijan: "zone7",
  Bangladesh: "zone7",
  Bhutan: "zone7",
  Brunei: "zone7",
  Cambodia: "zone7",
  China: "zone7",
  "East Timor": "zone7",
  Georgia: "zone7",
  "Hong Kong": "zone7",
  India: "zone7",
  Indonesia: "zone7",
  Japan: "zone7",
  Kazakhstan: "zone7",
  "Korea, South": "zone7",
  "Korea, North": "zone7",
  Kyrgyzstan: "zone7",
  Laos: "zone7",
  Macau: "zone7",
  Malaysia: "zone7",
  Maldives: "zone7",
  Mongolia: "zone7",
  Myanmar: "zone7",
  Nepal: "zone7",
  Pakistan: "zone7",
  Palau: "zone7",
  Philippines: "zone7",
  Singapore: "zone7",
  "Sri Lanka": "zone7",
  Taiwan: "zone7",
  Tajikistan: "zone7",
  Thailand: "zone7",
  Turkmenistan: "zone7",
  Uzbekistan: "zone7",
  Vietnam: "zone7",

  // Zone 8 - Americas & Oceania
  "American Samoa": "zone8",
  Anguilla: "zone8",
  "Antigua and Barbuda": "zone8",
  Argentina: "zone8",
  Aruba: "zone8",
  Bahamas: "zone8",
  Barbados: "zone8",
  Belize: "zone8",
  Bermuda: "zone8",
  Bolivia: "zone8",
  Bonaire: "zone8",
  Brazil: "zone8",
  "Cayman Islands": "zone8",
  Chile: "zone8",
  Colombia: "zone8",
  "Cook Islands": "zone8",
  "Costa Rica": "zone8",
  Cuba: "zone8",
  Dominica: "zone8",
  "Dominican Republic": "zone8",
  Ecuador: "zone8",
  "El Salvador": "zone8",
  "Falkland Islands": "zone8",
  Fiji: "zone8",
  "French Guiana": "zone8",
  Grenada: "zone8",
  Guadeloupe: "zone8",
  Guam: "zone8",
  Guatemala: "zone8",
  Guyana: "zone8",
  Haiti: "zone8",
  Honduras: "zone8",
  Jamaica: "zone8",
  Kiribati: "zone8",
  "Mariana Islands": "zone8",
  "Marshall Islands": "zone8",
  Martinique: "zone8",
  Micronesia: "zone8",
  Montserrat: "zone8",
  Nauru: "zone8",
  "New Caledonia": "zone8",
  "New Zealand": "zone8",
  Nicaragua: "zone8",
  Niue: "zone8",
  Panama: "zone8",
  "Papua New Guinea": "zone8",
};
